{{- if eq .Values.storage.type "local" -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-{{ .Release.Namespace }}-{{ include "redis-ha.fullname" . }}-server-data1
  labels:
    {{- include "redis-ha.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.storage.reclaimPolicy }}
  local:
    path: {{ .Values.storage.path }}1/
  volumeMode: Filesystem
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: data-{{ include "redis-ha.fullname" . }}-server-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storage.local.node }}
{{- end -}}
