{{- if not .Values.imagePullSecrets.existing -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-ha.fullname" . }}-regcred
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.regcred | b64enc }}
{{- end -}}
