apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-ha.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-ha.labels" . | nindent 4 }}
type: Opaque
data:
  auth: {{ .Values.redisPassword | b64enc }}
