apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-ha.fullname" . }}-announce-0
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-ha.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
  - name: redis
    port: {{ .Values.service.redis.port }}
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: {{ .Values.service.sentinel.port }}
    protocol: TCP
    targetPort: sentinel
  - name: exporter
    port: {{ .Values.service.redisExporter.port }}
    protocol: TCP
    targetPort: exporter-port
  selector:
    {{- include "redis-ha.selectorLabels" . | nindent 4 }}
    "statefulset.kubernetes.io/pod-name": {{ include "redis-ha.fullname" . }}-server-0
